.TH man 1 "24 Aug 2022" "1.0" "afc man page"
.SH NAME
afc \- Anime File Checker
.SH SYNOPSIS
afc [-C|-D] FILES
.SH DESCRIPTION
afc is a imple file checker with neither frills nor extra bells and whistles.

It takes a file / list of files and calculates the CRC32 for each.
Subsequently, it checks whether the CRC32 can be found in the filename.
.SH OPTIONS
.IP -C
force colour even when output is not a TTY.
.IP -D
disable colour even when output is a TTY.
.IP -h,--help
show usage help.
.SH EXIT CODES
.IP 1
if any file could not be accessed.
.IP 2
if any CRC error occured.
.SH BUGS
No known bugs.
.SH AUTHOR
Oliver Freyermuth (o.freyermuth@googlemail.com)
